### PR TITLE
Fix jQuery 3.x compatibility

### PR DESCRIPTION
**Pull request by SparkDragon**

### CODE REVIEW

**Comment by alexshnur** [comment]
Thanks i fixed

**Comment by sanjay8090** [comment]
Hi @alexshnur i am using this and notice that its not working with colspan and rowspan

**Comment by alexshnur** [comment]
Hi @sanjay8090 this is plugin only for thead columns
Look at demo http://alexshnur.github.io/drag-n-drop-table-columns/

**Comment by sanjay8090** [comment]
Hi @alexshnur  i know its for thead column but when we have table something like ths its not working 





<table>
  <tr>
    <th draggable="true" rowspan="2">dffddfdm</th>
    <th draggable="true" rowspan="2">affffff</th>
    <th draggable="true" colspan="2">fdgfdsfdsfds</th>
    <th draggable="true" colspan="2">sfdbgdfsgfdfd</th>
    <th draggable="true" colspan="2">fdggfdfhgd</th>
  </tr>
  <tr>
    <th>fdfdfddffdv</th>
    <th>gfddfdfv</th>
    <th>rterrtttld</th>
    <th>iuiutyyyyld</th>
    <th>oooooge</th>
    <th>lllllge</th>
  </tr>
  <tr>
    <td>No</td>
    <td>yes</td>
    <td>$366</td>
    <td>$556666</td>
    <td>140 Kg</td>
    <td>8700 kg</td>
    <td>vvvvv</td>
    <td>bbbbb</td>
  </tr>
  <tr>
    <td>yes</td>
    <td>no</td>
    <td>$40</td>
    <td>$40000</td>
    <td>5 Kg</td>
    <td>50 kg</td>
    <td>jjjjj</td>
    <td>ppppppp</td>
  </tr>
</table>

kindly check at your end what is issue which i am saying using above table

**Comment by alexshnur** [comment]
@sanjay8090 look at readme... no coments...

**Pull request closed without merging**
